import React,{useEffect,useState} from 'react';
import {fetchPolicy,simulatePolicy} from './api';
import type {PolicyEvaluation,PolicyInspection,PolicyRule} from './types';

export function PolicyInspector(){
 const[policy,setPolicy]=useState<PolicyInspection>();const[result,setResult]=useState<PolicyEvaluation>();const[selected,setSelected]=useState<PolicyRule>();const[error,setError]=useState('');const[action,setAction]=useState('git_push');const[kind,setKind]=useState('command');const[command,setCommand]=useState('git push origin main');const[path,setPath]=useState('');const[agent,setAgent]=useState('codex');const[environment,setEnvironment]=useState('development');
 useEffect(()=>{void fetchPolicy().then(setPolicy).catch(e=>setError(String(e)))},[]);
 const simulate=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{setResult(await simulatePolicy({action,kind,command:command.split(/\s+/).filter(Boolean),path,agent,environment}))}catch(reason){setError(String(reason))}};
 return <section className="policy-page"><header className="run-header"><div><div className="eyebrow">POLICY INSPECTOR · READ ONLY</div><h1>Active safety controls</h1><p>Inspect deterministic rules and run transient preflight simulations.</p></div><span className="role">Viewer-safe · no policy writes</span></header>{error&&<div className="error" role="alert">{error}</div>}{policy&&<><div className="metadata-strip"><span><small>FINGERPRINT</small><code>{policy.fingerprint}</code></span><span><small>SOURCES</small><b>{policy.sources.length}</b></span><span><small>RULES</small><b>{policy.rule_count}</b></span><span><small>DEFAULT</small><b>{policy.default.risk} / {policy.default.decision}</b></span><span><small>HEALTH</small><b>{policy.health}</b></span></div><div className="policy-grid"><section className="policy-rules"><div className="section-head"><h2>Effective rules</h2><span>{policy.rule_count} ordered rules</span></div><div className="policy-table" role="table">{policy.rules.map(rule=><button key={`${rule.source}/${rule.id}`} onClick={()=>setSelected(rule)} className={selected?.id===rule.id?'selected':''}><code>{rule.id}</code><span>{rule.source}</span><span>{rule.kind||'any'} {rule.command_regex||'all'}</span><b>{rule.risk}</b><b>{rule.decision}</b><span>P{rule.priority}</span></button>)}</div>{selected&&<RuleDetail rule={selected}/>}</section><section className="simulation"><h2>Simulate action</h2><form onSubmit={simulate}><label>Action<input value={action} onChange={e=>setAction(e.target.value)} required/></label><label>Kind<select value={kind} onChange={e=>setKind(e.target.value)}><option>command</option><option>file_change</option><option>git</option><option>mcp_call</option><option>rollback</option></select></label><label>Command<input value={command} onChange={e=>setCommand(e.target.value)}/></label><label>Path / target<input value={path} onChange={e=>setPath(e.target.value)}/></label><label>Agent<input value={agent} onChange={e=>setAgent(e.target.value)}/></label><label>Environment<input value={environment} onChange={e=>setEnvironment(e.target.value)}/></label><button type="submit">Simulate</button></form>{result&&<SimulationResult result={result}/>}</section></div></>}</section>
}
function RuleDetail({rule}:{rule:PolicyRule}){return <aside className="rule-detail"><span className="eyebrow">RULE DETAIL</span><h3>{rule.name||rule.id}</h3><dl className="facts"><dt>Rule ID</dt><dd><code>{rule.id}</code></dd><dt>Source / priority</dt><dd>{rule.source} · {rule.priority}</dd><dt>Conditions</dt><dd>{rule.kind||'any kind'} · <code>{rule.command_regex||'any command'}</code></dd><dt>Risk / decision</dt><dd>{rule.risk} · {rule.decision}</dd><dt>Reason</dt><dd>{rule.description||'Stable rule result; no additional description.'}</dd></dl></aside>}
function SimulationResult({result}:{result:PolicyEvaluation}){return <div className="simulation-result" aria-live="polite"><div className="decision"><span><small>RISK</small><b>{result.risk_level}</b></span><span><small>DECISION</small><b>{result.decision}</b></span></div><p>{result.reason}</p><h3>Matched rules</h3>{result.matched_rules.length?result.matched_rules.map(rule=><div className="trace" key={rule.rule_id}><code>{rule.source}/{rule.rule_id}</code><span>{rule.risk_level} · {rule.decision}{rule.overridden?' · overridden':''}</span></div>):<p className="muted">No rule matched; default applied.</p>}<details open><summary>Deterministic trace</summary>{result.trace.map((step,index)=><div className="trace" key={index}><code>{step.rule_id||'default/final'}</code><span>{step.message}</span></div>)}</details><small>Fingerprint {result.policy_fingerprint}</small></div>}
